import { precacheAndRoute } from 'workbox-precaching'

// Precache all assets generated by the build
precacheAndRoute(self.__WB_MANIFEST)

// Handle push notifications
self.addEventListener('push', (event) => {
    if (!event.data) return

    try {
        const data = event.data.json()
        const options = {
            body: data.body,
            icon: data.icon || '/logo-192.png',
            badge: data.badge || '/logo-192.png',
            data: {
                url: data.url || '/'
            }
        }

        event.waitUntil(
            self.registration.showNotification(data.title, options)
        )
    } catch (err) {
        console.error('Push event error:', err)
    }
})

// Handle notification clicks
self.addEventListener('notificationclick', (event) => {
    event.notification.close()
    const urlToOpen = event.notification.data.url || '/'

    event.waitUntil(
        clients.matchAll({ type: 'window', includeUncontrolled: true }).then((windowClients) => {
            // If a window is already open, focus it
            for (let i = 0; i < windowClients.length; i++) {
                const client = windowClients[i]
                if (client.url === urlToOpen && 'focus' in client) {
                    return client.focus()
                }
            }
            // Otherwise, open a new window
            if (clients.openWindow) {
                return clients.openWindow(urlToOpen)
            }
        })
    )
})
